### ISSUE TITLE
Crash on level intermission screen

### ISSUE THREAD

**Issue by GuntherDW** [svkaiser/Doom64EX#10]
In the options->settings menu, if you set texture fit forcibly to "scaled" and exit a level, it'll crash at gl_ResampleTexture. More specifically by checking at the crashlog it's crashing on the "EVIL" texture.

I'm just winging it but it looks like the ratios look a bit wonky. It resamples it to 256*256, and crashes in that method.
What's weird is that even though I compiled with debugging symbols enabled, gdb mentions one of the inWidth/inHeight to be "<optimized out>". But that might just be because of my compiler. I'm using GCC 5.3.0-gentoo (gcc (Gentoo 5.3.0 p1.0, pie-0.6.5) 5.3.0)

**Comment by dotfloat** [comment]
Thanks.

This problem is related to #2 and will be fixed when I get around to writing proper image manipulation and have a better look at the graphics code.

If you need this feature, I can hack around it the same way I did for #2.

**Comment by GuntherDW** [comment]
I don't **need** the feature. I just found it weird that after fiddling around with the setting menu it took me a while to figure out what exactly was causing the crashes. Both look almost the same so whatever.

**Comment by dotfloat** [comment]
The new Pixmap API fixed this issue. Stretching the textures looks horrible, so I'll remove this "feature" at a later date.
