### ISSUE TITLE
MSVC 16 compiler errors on i_main.cc

### ISSUE THREAD

**Issue by TheThunderGuyS** [svkaiser/Doom64EX#108]
I'm relatively new to building things and was trying to compile the latest version of this project. I successfully created the build files but after compiling, there are 17 errors all in `src/engine/system/i_main.cc` between line 443 and 448. I have no knowledge of C++ so I don't know how I would fix this but because of the errors I can't build Doom64EX. 

This is on 64-bit Windows 10 1909 with a MSVC 16 compiler and the latest Windows 10 SDK.
The exact errors are as follows:
![image](https://user-images.githubusercontent.com/52540509/81085613-6efd0a80-8ec5-11ea-9c89-e466b8c8f0c5.png)

The lines affected (442 - 449):
```c++
int D_abs(int x) {
    __asm {
        mov eax,x
        cdq
        xor eax,edx
        sub eax,edx
    }
}
```

I followed the same instructions for building on Win32 in the readme so if I did anything wrong, help would be nice.

**Comment by Serosis** [comment]
Visual Studio doesn't support inline assembly for 64-bit solutions.

You'd have to convert the assembly to C++.
