### ISSUE TITLE
No sound after "unstable" merge

### ISSUE THREAD

**Issue by GuntherDW** [svkaiser/Doom64EX#11]
I updated my git branch ,but specifically since commit 10eb9f18e9b2ef06bc063119f5a5930f4355f253 (Merge remote-tracking branch 'origin/unstable') the sound doesn't want to work. I use pulseaudio on my desktop, and I can see no registration of a audio stream, whereas the older ones, with the exact same config just works. (well, almost the same config, seeing as it no longer is stored in ~/.doom64ex/)

startup log from new version : http://pastebin.com/7t5n9gSe
startup log from old version : http://pastebin.com/jVwncQRu

I tried setting it to another output method with the following results :

oss nags about /dev/dsp being in use, which is correct, and seeing as I have no hardware mixing available is expected,
alsa doesn't give me sound either (neither does it register an audio stream, which it should because default audio is routed through pulseaudio),
file generates a file in the root folder called fluidsynth.raw but has nothing really of any value in it, and is only a couple bytes big.

running the engine through a wrapper like padsp also results in no actual audio stream being registered, even though the "in use" errors in the startup log disappear.

I'm not really sure where to start looking first because that commit is quite a big one, but I'll see what I can come up with.

**Comment by dotfloat** [comment]
Lol. That's what I get for testing without sound on.

The problem is that it can't find the DOOMSND.SF2 file, so it shouldn't take long to fix.

**Comment by dotfloat** [comment]
Fixed! You'll need to regenerate kexdata.wad with cmake.

Turns out I just accidentally added a few text files into the midi track section of the wad.
