### ISSUE TITLE
Script breakage with the kexplus merge?

### ISSUE THREAD

**Issue by GuntherDW** [svkaiser/Doom64EX#12]
It seems like when you load a saved game, it doesn't really seem to load the script sequences correctly.

For example the first map, the last open room has a light that "circles" around the room. However, when you save and load the game, only 1 sector lights up, and the rest just stay dark.

https://youtu.be/t2n7opbewVg?t=198
This isn't my video but that is the room I'm talking about.

EDIT: Hmm, the crusher sequence when you grab the soulsphere in hectic however does seem to trigger and continue just fine when you load up a saved game. Might be something else at play here.

**Comment by dotfloat** [comment]
The win32 d64ex 2.5 doesn't have this problem. Loading the save from 2.5 with git d64ex has the same result, which suggests that the bug is somewhere in p_saveg.c

**Comment by dotfloat** [comment]
This might have been fixed now. Haven't tested it extensively. Please confirm if you can.

**Comment by GuntherDW** [comment]
Sorry for the late response but I kind of forgot to test this.

I just now tested it with a fresh save and it indeed does work.
If you load up a save made with the broken build it only lights up 1, but a new save will work as it should.

**Comment by dotfloat** [comment]
Alright, thanks!
