### ISSUE TITLE
CMake build scripts are outdated?

### ISSUE THREAD

**Issue by GuntherDW** [svkaiser/Doom64EX#14]
When doing a fresh git clone and trying to build, I got this error during the cmake process.

The kexlib Cmake files apparently expect the folder to be there, but it's either not committed or the files are outdated?

[cmake stuff]
-- Found Threads: TRUE  
CMake Error at src/kexlib/CMakeLists.txt:61 (file):
  file COPY cannot find "/GuntherDW/src/git/Doom64EX/data/kexlib_test".

-- Found SDL2: /usr/include/SDL2 (found version "2.0.4") 
[more cmake log]
-- Configuring incomplete, errors occurred!
See also "/GuntherDW/src/git/Doom64EX/build/CMakeFiles/CMakeOutput.log".
See also "/GuntherDW/src/git/Doom64EX/build/CMakeFiles/CMakeError.log".

**Comment by dotfloat** [comment]
Yes, that'd be me being a idiot who forgot to upload the test png. You can disable tests by running `cmake` with `-DTESTING=OFF` an as argument.

There haven't been any substantial commits for a few months anyway. But, I'm planning on doing some (rather uninteresting) changes this weekend.
