### ISSUE TITLE
Launcher source missing

### ISSUE THREAD

**Issue by leilei-** [svkaiser/Doom64EX#20]
This is a peculiar omission

(long story short i was hoping to rip off the launcher to quickly prototype an OA launcher)

**Comment by dotfloat** [comment]
You can find the original launcher source in the old SourceForge repo: https://sourceforge.net/p/doom64ex/code/HEAD/tree/trunk/src/launcher/

It's unlikely that future versions of D64EX will ship with a separate launcher program.
