### ISSUE TITLE
Trouble building on Debian 8

### ISSUE THREAD

**Issue by ProfessorKaos64** [svkaiser/Doom64EX#22]
### Details:

This project builds and links with the manual steps in the readme, but the build system choices here don't work with dpkg-buildpackage

* OS: Debian 8 / SteamOS
* [Debian files](https://github.com/ProfessorKaos64/LibreGeek-Packaging/tree/brewmaster/doom64ex/debian)
* Build Log: http://sprunge.us/bCIF

```
[ 83%] Building C object src/engine/CMakeFiles/doom64ex.dir/system/i_system.c.o
/build/doom64ex-0.20160530+git+bsos/src/engine/system/i_system.c: In function 'I_Printf':
/build/doom64ex-0.20160530+git+bsos/src/engine/system/i_system.c:680:5: error: format not a string literal and no format arguments [-Werror=format-security]
     printf(buff);
     ^
cc1: some warnings being treated as errors
src/engine/CMakeFiles/doom64ex.dir/build.make:1779: recipe for target 'src/engine/CMakeFiles/doom64ex.dir/system/i_system.c.o' failed
make[4]: *** [src/engine/CMakeFiles/doom64ex.dir/system/i_system.c.o] Error 1
make[4]: Leaving directory '/build/doom64ex-0.20160530+git+bsos/Build'
CMakeFiles/Makefile2:207: recipe for target 'src/engine/CMakeFiles/doom64ex.dir/all' failed
make[3]: *** [src/engine/CMakeFiles/doom64ex.dir/all] Error 2
make[3]: Leaving directory '/build/doom64ex-0.20160530+git+bsos/Build'
Makefile:117: recipe for target 'all' failed
```

What could be going wrong here?

**Comment by ProfessorKaos64** [comment]
false alarm it seems

**Comment by dotfloat** [comment]
Hey. Apologies for not answering sooner.

The issue here is that `dpkg-buildpackage` is a bit too strict in what's allowed in the code (I say 'too strict', but I really mean that d64ex is not up to snuff). It'll take a while to fix all issues.

**Comment by ProfessorKaos64** [comment]
Thank you for acknowledging this. I'll build locally for now. Will the project (now that it seems be back in gear) have any milestones listed for this? Anything to check back on for this?

**Comment by dotfloat** [comment]
Yes. I intend to set up a build server that can generate .deb's, among other things. This will be fixed before a proper release.

I'll keep you posted.

**Comment by ProfessorKaos64** [comment]
I'll continue to keep building myself still, to ensure everything is smooth on SteamOS with the available package pool
