### ISSUE TITLE
Linux x64: Neiher 'kex.wad' nor 'kexdata.wad' are generated by CMake.

### ISSUE THREAD

**Issue by aFoxNamedMorris** [svkaiser/Doom64EX#23]
I get no errors configuring or compiling, but I was forced to try and create 'kex.wad' manually. The levels load, and everything seems functional, except that all the PNG graphics are white boxes.

I'm on Xubuntu 15.10 64-bit.

**Comment by dotfloat** [comment]
This is related to #16. The 'correct' way to build `kex.wad` is to do `make kexwad` after using CMake. It'll happen automatically after doing `make` in a future commit.

Thanks.

**Comment by aFoxNamedMorris** [comment]
Thank you! may be a good idea to add that to the instructions.
