### ISSUE TITLE
Linux x64: No crosshairs.

### ISSUE THREAD

**Issue by aFoxNamedMorris** [svkaiser/Doom64EX#25]
The crosshairs section is stuck in the 'off' position in the menu. Setting via console yields no result either.

**Comment by dotfloat** [comment]
The crosshairs "work" for me. ie: I can change them and they stay put when I restart the game.

They just don't work correctly due to the Pixmap API stuff. (It will be fixed shortly, just gotta not fail all of my exams.)

**Comment by aFoxNamedMorris** [comment]
School is important. Take your time.

**Comment by dotfloat** [comment]
This might have been fixed. Can you confirm?

**Comment by aFoxNamedMorris** [comment]
My computer is in need of repairs and is currently inoperable. I will test once I have repaired it. Sorry.

**Comment by dotfloat** [comment]
No rush, dude.

**Comment by dotfloat** [comment]
Closing this issue. Reopen if this issue persists.
