### ISSUE TITLE
Executable icon

### ISSUE THREAD

**Issue by alexey-lysiuk** [svkaiser/Doom64EX#26]
Currently there is no icon for executable.
Author of [the pretty good Doom 64 icons](http://thedoctor45.deviantart.com/art/Doom-64-Custom-Icon-364632626) allowed to use his work. The package contains all required formats.
What do you think about it?

**Comment by dotfloat** [comment]
Oh, right, the one in the repo only 9 bytes for whatever reason. (The sourceforge one is also corrupted.)

I don't mind this design, but it'd need some tweaking for it to look nice at 16x16.

Ultimately it's up to @svkaiser.

**Comment by ProfessorKaos64** [comment]
I don't mind tweaking the icons if help is needed. I could also create a Steam banner (can't check the link right now, work).
