### ISSUE TITLE
Errors on latest build - SteamOS /Debian Jessie

### ISSUE THREAD

**Issue by ProfessorKaos64** [svkaiser/Doom64EX#30]
Lots of errors see the log below, starting at line 1139. There are quite a few, so no snipped here.

Full log: https://gist.github.com/ProfessorKaos64/620eb20303b046767f51f8b1271b235b#file-errors-L1139

My package build, linked below, builds without error (30-Jul-2016 16:09):

http://packages.libregeek.org/steamos-tools/pool/games/d/doom64ex/

To try and help myself with stability, going to fork just to get stable snaps for myself.

**Comment by dotfloat** [comment]
The version that I merged requires GCC 5.

I'd like to try and get away with using a newer C++ standard, but that might mean that you'll have a hard time compiling it on Debian.

**Comment by ProfessorKaos64** [comment]
ah... ok, which is not in debian jessie. That's a problem for me. Building that is rough, unless you plan on supporting something easier to backport (which I have), such as clang/llvm. I'll have to stick with the version I have for the foreseeable future.

**Comment by dotfloat** [comment]
Seems like clang 3.4 has the required features, and jessie has 3.5 already.

**Comment by ProfessorKaos64** [comment]
I have no problem trying and usign clang if it works. I'll try with clang, e.g. `export CC=clang`

**Comment by dotfloat** [comment]
More important is `export CXX=clang++`.

**Comment by ProfessorKaos64** [comment]
No luck with clang. Looking further here.. http://sprunge.us/PEOK

**Comment by ProfessorKaos64** [comment]
I'll just keep checking out the build errors, and code updates from time to time. One example:

```
/build/doom64ex-0.20160801+git+bsos/include/kex/kexdef:35:27: note: 
      expanded from macro 'ALIAS_FN'
    inline decltype(auto) NewName(Args&&... args)     \
                          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

See: http://stackoverflow.com/questions/12972881/clang-c-requires-a-type-specifier

**Comment by dotfloat** [comment]
There. It compiles in my Jessie VM.

**Comment by ProfessorKaos64** [comment]
if I do a build with:

```
export CC=clang
export CXX=clang++
rm  -rf build && mkdir build
cd build && cmake .. && make
```

I get this: http://slexy.org/view/s2wd4kKmSR

**Comment by ProfessorKaos64** [comment]
This worked for me, mostly (need to check some installed files), but the build finished: [debian/rules](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/doom64ex/debian-master/rules). Any changes you'd make there? or include in a cmake setting in the code?

**Comment by dotfloat** [comment]
[You don't need to set these `CMAKE_*` defines.](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/doom64ex/debian-master/rules#L15-L18)

CMake figures out what compiler it uses based on `CC` and `CXX`. `-std=c99` has been default for a long time and my `CMakeFiles.txt` uses `-std=c++14`. (Well, technically `c++1y == c++14`, so it doesn't matter.)

But that's me being pedantic. If it compiles it compiles.

I'm assuming everything is ok, so I'm closing this.

**Comment by ProfessorKaos64** [comment]
I noted above, the standard build I used did not work.

```
#!/usr/bin/make -f

# Upstream now using gcc5, which Jessie does not have
# Use clang

export CC=clang
export CXX=clang++

%:
	dh $@

override_dh_auto_configure:
	rm -rf build && mkdir -p build
	cd build && cmake . && make
```

**Comment by dotfloat** [comment]
Try with `-DCMAKE_BUILD_TYPE=Release`

**Comment by ProfessorKaos64** [comment]
Nope, hard stop seems to be (full log above):

```
error: debug information for auto is not yet supported
error: debug information for auto is not yet supported
2 errors generated.
src/kexlib/CMakeFiles/kexlib.dir/build.make:100: recipe for target 'src/kexlib/CMakeFiles/kexlib.dir/gfx/Image.cc.o' failed
```

**Comment by dotfloat** [comment]
The `error: debug information for auto is not yet supported` is because it's trying to create debug info, which it doesn't need to. Maybe the packaging tool tries to automatically create a `-dbg` version?

**Comment by ProfessorKaos64** [comment]
I had clang-3.8 backported in my testing repo, which continues past that error. Some backstory [here](https://llvm.org/bugs/show_bug.cgi?id=16876). Hmm. If I do keep the cmake defines, I can use clang  3.5 from jessie. 3.5 should be fine if I think a flag is defined to not care about that debug info.
