### ISSUE TITLE
Incorrect saving of total sercrets for some levels

### ISSUE THREAD

**Issue by gogtytsufvhgekwzyuow** [svkaiser/Doom64EX#35]
For some reason the game incorrectly saves a total number of secrets and it is incremented after each save by the same specific value for a level. So you can not achieve 100% if saved in this levels.

For example, in map6 you have 3 total secrets. If you saved and then loaded - the game starts thinking that it is 5. If you saved again, after loading the game start thinking that total secrets is 7 for this level.

I tested every level, the bug 100% happens in these levels for me:
Map 06 - +2 (3, 5, 7, 9)
Map 10 - +7 (7, 14, 21, 28)
Map 11 - +2 (4, 6, 8, 10)
Map 14 - +1 (1, 2, 3, 4)
Map 29 - +4 (6, 10, 14, 18)
Map 30 - +1 (2, 3, 4, 5)

All other maps are without this bug.

**Comment by gogtytsufvhgekwzyuow** [comment]
It is may be already fixed and i just used old build (from https://doom64ex.wordpress.com/)
If it really already fixed for all maps you can just close this thread, sorry.

**Comment by dotfloat** [comment]
Hey. This should be fixed already. Thanks for the bug report anyway. I'd much rather have duplicate bug reports than none at all. :smile:

Also, thanks for reminding me that I've yet to create snapshot builds for Windows.
