### ISSUE TITLE
Crashes with Segmentation Fault in Ubuntu 16.10

### ISSUE THREAD

**Issue by aynrandjuggalo1** [svkaiser/Doom64EX#44]
I'm not an expert on compiling programs from source. I'm compiling this code on a pretty stock install of Ubuntu 16.10. However, the game is unplayable because it frequently crashes with a "Segmentation Fault"!

Is Ubuntu 16.10 the problem? I'm willing to change distros. What should I do?

**Comment by dotfloat** [comment]
No, Ubuntu 16.10 is definitely not the problem.

When did you compile this and do you do anything special for the crashes to occur?

**Comment by aynrandjuggalo1** [comment]
I compiled it just yesterday. The crashes seem to occur in roughly the same spot, a corridor in the first level extremely early on (the spot just after the third enemy). Could my WAD be the problem? If I generated the WAD from a bad ROM, would that be causing the crashes?

**Comment by ProfessorKaos64** [comment]
@aynrandjuggalo1 , it's possible. I have used this on Debian 8 and SteamOS without issue. Not sure if it would help, but [here](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/doom64ex/debian/control) are the dependencies I list for the package I generate.

**Comment by AXDOOMER** [comment]
> If I generated the WAD from a bad ROM, would that be causing the crashes?

You used version 1.0 or version 1.1? There are two Doom USA ROMs. I don't know the difference between both.

**Comment by dotfloat** [comment]
I'm pretty sure [this bugreport](http://z13.invisionfree.com/Doom64EX/index.php?showtopic=170&view=findpost&p=40001459) is the cause. I'm hoping to fix it today.

**Comment by dotfloat** [comment]
Wasn't fixed today, but it's "fixed". (Gamma doesn't segfault, but doesn't look good either).
