### ISSUE TITLE
Make mode setting work without restart

### ISSUE THREAD

**Issue by Harvie** [svkaiser/Doom64EX#50]
It would be pretty nice to have fullscreen mode. Idealy with some shortcut to switch it on and off during gameplay...

**Comment by dotfloat** [comment]
There is a fullscreen mode already.

**Comment by Harvie** [comment]
But when i switch to some other window (eg. alt+tab) it stays windowed even after i switch back and there's no way to switch it back to fullscreen without restarting game.

Why i need to restart game to enable fullscreen, but i don't need restart game to disable it?

**Comment by dotfloat** [comment]
Yeah, it's a problem that was not fixed mainly because the Menu system is a pain to work with. (Need it for the "Do you want to keep your settings?" screen)

Which version are you on and on which operating system?

**Comment by Harvie** [comment]
ArchLinux, doom64ex-git r245.e89de24-1

**Comment by dotfloat** [comment]
The video mode is now set immediately when exiting the menu. It's also possible to switch between windowed and fullscreen with `Right Alt + Enter`. It's not very nice, but it'll do until the menu code is rewritten.

Thanks for the bug report. If you have any problems feel free to reopen this issue.
