### ISSUE TITLE
Going to load game causes crash with recent commits

### ISSUE THREAD

**Issue by shoober420** [svkaiser/Doom64EX#52]
With the recent commits just made, Doom64ex crashes when going to load game screen. I'm on Arch Linux and my full system specs are in my steam profile, which is linked in my GitHub page. I'll post the error from the terminal when I get home from work.

**Comment by shoober420** [comment]
Here is the error:

Error - Z_Free: freed a pointer without ZONEID 
(~/Downloads/packages/doom64ex-git/src/Doom64EX/src/engine/playloop/p_saveg.cc:1349)

**Comment by dotfloat** [comment]
The one save I had seems to work now. I did some minor changes earlier that *might* affect saving or loading, so backup your saves! (They shouldn't but my hand sometimes slips and I write bad code :P)

Thanks.

**Comment by shoober420** [comment]
Awesome! This fixed the crash. Happy Holidays sir.
