### ISSUE TITLE
Integrate Wadgen better into the rest of the codebase.

### ISSUE THREAD

**Issue by dotfloat** [svkaiser/Doom64EX#6]

**Comment by alexey-lysiuk** [comment]
If I got it right this task is about .wad/.sf2 created from a ROM.
How about searching for a ROM in user's directory by know extensions (if no generated files found) and generate .wad/.sf2 on the fly?
I'm thinking of a good cross-platform solution and this seems to be OK to me.
There are some issues of course (no progress, no error reporting, etc) but I guess they cannot be solved without writing UI-based WAD generation solution for each platform. SDL2 has platform agnostic message boxes but no open dialog or more complex controls.
