### ISSUE TITLE
Game stalls at end of level stats screen

### ISSUE THREAD

**Issue by Manuel-K** [svkaiser/Doom64EX#61]
Until I alt+tab out of it. It does not matter if it is the normal exit or the secret level exit. If I enable "screen melt", I even have to alt+tab before the melting starts.

Before I spend time investigating – does this happen for anybody else? Or is it this crappy laptop?

**Comment by dotfloat** [comment]
Can't reproduce. The melt effect is located in `r_wipe.cc`. I believe `WIPE_MeltScreen` is responsible for it.

**Comment by Manuel-K** [comment]
Weird.

**Comment by Manuel-K** [comment]
The problem does only occur in full screen mode. Everything works as expected if the game runs in a window. And it is independent of the selected resolution.

**Comment by dotfloat** [comment]
Nope. Tried recreating on several computers and the result is the same. What is your hardware configuration?

**Comment by Manuel-K** [comment]
I'm unable to reproduce the issue at the moment. Weird.
