### ISSUE TITLE
Crash in middle first level

### ISSUE THREAD

**Issue by DongVGH** [svkaiser/Doom64EX#66]
While im in the first level, the game may crash at random times, its not impossible to finish the level, but still pretty hard, does not happen on any other levels.

Crashlog.txt contents: http://pastebin.com/Cjnczsy0

**Comment by dotfloat** [comment]
Hey. This is due to your `i_gamma` setting and has already been fixed. Your game crashes when you look at the blue key door, right? The workaround is to set `i_gamma` to 0.

If this doesn't fix the crash, feel free to reopen this issue.
