### ISSUE TITLE
Missing CMakeList

### ISSUE THREAD

**Issue by shoober420** [svkaiser/Doom64EX#67]
When compiling, I get an error about the CMakeList missing. I'll post the error message after work.

**Comment by shoober420** [comment]
Here it is.

-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/lib/hardening-wrapper/bin/cc
-- Check for working C compiler: /usr/lib/hardening-wrapper/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/hardening-wrapper/bin/c++
-- Check for working CXX compiler: /usr/lib/hardening-wrapper/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:99 (add_subdirectory):
  The source directory

    /home/jukilo420_-/Downloads/packages/doom64ex-git/src/Doom64EX/fluidsynth

  does not contain a CMakeLists.txt file.


-- >>
-- Found SDL2: /usr/include/SDL2 (found version "2.0.5")
-- Found SDL2_net: /usr/include/SDL2 (found version "2.0.1")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")
-- Found PNG: /usr/lib64/libpng.so (found version "1.6.28")
-- Found OpenGL: /usr/lib64/libGL.so
-- Configuring incomplete, errors occurred!
See also "/home/jukilo420_-/Downloads/packages/doom64ex-git/src/Doom64EX/temp/CMakeFiles/CMakeOutput.log".

**Comment by alexey-lysiuk** [comment]
**fluidsynth-lite** is a submodule. Read answers [here](https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules) about proper way to clone or update your local repo.

**Comment by dotfloat** [comment]
You'll need to run `git submodule --init --recursive`. I'll add it to the README.

**Comment by shoober420** [comment]
OK, I compile using the options in the PKGBUILD that comes in the Arch AUR doom64ex-git package. I notified the maintainer and told him to update the PKGBUILD. Thank you.
