### ISSUE TITLE
Mouse completely broken on all Windows 10 systems with Fall update.

### ISSUE THREAD

**Issue by NOFUNEVER** [svkaiser/Doom64EX#72]
View snaps back to starting position the moment mouse stops moving. Cannot turn or aim subsequently. I've tested this on many machines, present on all Win 10 systems with Fall update. Compatibility mode has no effect. Basically unplayable. Forum suggested nightly build in post 5 has working mouse but no sound.  https://www.tapatalk.com/groups/doom64ex/doom-64-ex-mouse-not-working-t219.html?sid=d173a9fd7f00a641098335e71cb5daa6#p40003790

**Comment by dotfloat** [comment]
Seems like the SDL version bundled with the game is a bit out of date. Download a newer version from https://www.libsdl.org/release/SDL-1.2.15-win32.zip and replace the `SDL.dll` file.

**Comment by NOFUNEVER** [comment]
The nightly build was working after all I just forgot to copy the snd file along with the wad. I noticed the different sdls between release and working  nightly. Didn't think it would as simple as swaping  the dll out. Thanks ill give it a try. Might want to update the instructions/bundle saw a lot of unanswered posts scattered online about it. Figured I'd go to the "source" to ask questions lol, thanks for prompt reply.

**Comment by dotfloat** [comment]
Thank you very much for the bug report. I got Kaiser to update the download thing, hopefully that should be good for the future.

I'm closing this. Feel free to reopen this issue if you find anything else that's wing with the fall update.
