### ISSUE TITLE
Please tag pre-file move and rename revision

### ISSUE THREAD

**Issue by haleyjd** [svkaiser/Doom64EX#73]
I need to be able to browse the source tree from a revision that predates every file being moved to subfolders and being renamed to .cc; github's interface will not allow this because it's too limited to understand git file moves. Please create a tag (or several) that points to some of these revisions so that the source history is browsable.

**Comment by dotfloat** [comment]
I've added a `2.5-sourceforge` tag and a `before-mass-rename` tag. If you need anything else just reopen this issue.

**Comment by dotfloat** [comment]
In case you want earlier history on Github, I've created a mirror of the sourceforge repository: https://github.com/dotfloat/Doom64EX-2.5

Now if it were possible to merge them... :/
