### ISSUE TITLE
Issue on map29 outpost omega

### ISSUE THREAD

**Issue by GuntherDW** [svkaiser/Doom64EX#8]
I'm running Doom64 EX on a gentoo, with the latest git from nov 25.
I had to create the wad and SF2 file using d64ex 2.5 with wine, which loaded correctly however.

There however seems to be an issue in one of the secret maps, particularly "Outpost Omega (map29)".
There is a certain shootable trigger on this map that will spawn the unmaker in the so called "yellow room".

link to a let's play on original hardware with the particular secret : https://youtu.be/sDDg4QYfYM8?list=PL4109CAF34427E32E&t=617

The button is there, but won't active by shooting it or activating it normally. I've checked out the rom used to create the wads in mupen64plus and it does indeed work in mupen64plus.
If I check out other LP's using d64ex they however get it to work. I could attempt to compile & run it through wine to see if it's this particular version that's causing it.

edit: using wine and Doom64EX 2.5 from Kaisers' wordpress site using the same resources I can get the unmaker using that trigger.
When I openend up a savegame that I made in the level on the windows version, it worked as well. I was able to trigger the switch without issues.

**Comment by GuntherDW** [comment]
There is a same kind of issue on the MAP17 "watch your step" map it seems.
There are 2 doors that you have to shoot on opposite ends to open doors with switches to access secret areas.

https://www.youtube.com/watch?v=xQCwYZG_Y2c

The first one which unlocks access to the invulnerability sphere works just fine, but shooting the other door doesn't trigger the other door on the other side.

**Comment by dotfloat** [comment]
Yeah, I can reproduce both of these.

The linedefs are there and are shootable (in theory), which means that the map loads correctly. It's quite strange that in MAP17 one of the switches work, while the other doesn't. Might have something to do with their orientation...

Thanks for the detailed bug report!

**Comment by dotfloat** [comment]
Fixed!

**Comment by GuntherDW** [comment]
Thanks for fixing both this and my other bug report. I'm doing a complete run through the game right now so if I find any other (besides (outdated) libpng and texture blackouts) I'll let you know :).
