### ISSUE TITLE
Issues compiling fluidsynth with GCC 7.3.0 (Gentoo)

### ISSUE THREAD

**Issue by GuntherDW** [svkaiser/Doom64EX#81]
Using a clean pull from the repo and fluidsynth repo GCC seems to trip over some code in the fluidsynth repo.

build log : https://paste.ee/p/LJqGk#yQB1f1plS6dluJrOm0VxFz0Oqgdg79mG

It seems to trip over a potential issue more than an actual error.

Versions:
 - GCC : gcc (Gentoo 7.3.0-r3 p1.4) 7.3.0
 - CMake : 3.11.4
 - Main repo : 5309f105a66c4ba62a15687d108bfd6fb073983a
 - FluidSynth repo : cdc8115d4f2d6e8280759bbe514ba15fa88053ea

**Comment by dotfloat** [comment]
Fixed this in `fluidsynth-lite` quite a while ago, but for whatever reason we weren't pointing to the correct commit. Should be good now hopefully. Update to the latest version with the following command:

```shell
$ git submodule update
```
