### ISSUE TITLE
Segmentation fault (core dumped) on wadgen

### ISSUE THREAD

**Issue by ShockwaveNN** [svkaiser/Doom64EX#87]
Hi I just compile Doom64Ex from source code and installed it on Ubuntu 18.04
on 
`doom64ex -wadgen doom.z64`
I get at end
```
Successfully created /home/lobashov/.local/share/doom64ex/doom64.wad
Writing Soundfont File...

Successfully created /home/lobashov/.local/share/doom64ex/doomsnd.sf2
Segmentation fault (core dumped)

```
But I tryed to run doom64ex after that - and it run fine (at least first level)

What can I do to give more information?

**Comment by dotfloat** [comment]
Oof. I thought I commented on this one already. Sorry for the late response.

No idea why it would crash. We're moving to using the ROM directly (see `rom` branch) so I'm not going to investigate this. It'll be merged in the near future.

Thanks.

**Comment by ShockwaveNN** [comment]
@dotfloat got it, no worries
