### ISSUE TITLE
Levelstats get "mangled" after a save/load.

### ISSUE THREAD

**Issue by GuntherDW** [svkaiser/Doom64EX#9]
Whilst playing I noticed that even though I got all of the secrets, it didn't count it as 100% all of the time.
After a while I noticed that saving and loading after getting a secret in a map changes the amount that doom64ex thinks is in the map.
This is easiest to demonstrate in MAP11: Terror core. There is a secret berserk pack right behind you at the start of the level.
Before saving it then says I got 1/4 secrets, which is correct. However, after I save and load that save, it says I have 1 out of 6 secrets.

Screenshot before loading the savegame : http://wrongplace.be/files/d64ex/BeforeSavingAndLoading.png
Screenshot after loading the savegame (notice the secret amount going up) : http://wrongplace.be/files/d64ex/AfterSavingAndLoading.png
I'm not entirely sure but I think this can happen to the other counters as well.

**Comment by dotfloat** [comment]
Should be fixed now. Thanks!
